# Generated by Django 4.2.11 on 2024-04-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageurl', '0003_rename_tag_id_urltag_tag_rename_url_id_urltag_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=15)),
                ('path', models.CharField(max_length=150)),
                ('data', models.CharField(max_length=225)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'log_error',
            },
        ),
    ]
